packages:
  - packages/*
  - apps/*

catalog:
  typescript: ^5.8.3
  vite: ^6.3.5
  vitest: ^3.2.0
  vite-tsconfig-paths: ^5.1.4
  '@vitejs/plugin-react-swc': ^3.10.1
  '@types/node': ^22.15.29
  motion: ^12.18.1
  react-scan: ^0.3.4
  usehooks-ts: ^3.1.1
  unplugin-dts: 1.0.0-beta.0
  '@microsoft/api-extractor': ^7.52.8

catalogs:
  react19:
    'react': ^19.1.0
    'react-dom': ^19.1.0
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5
  storybook9:
    'storybook': ^9.0.9
    '@storybook/builder-vite': ^9.0.9
    '@storybook/react-vite': ^9.0.9
    'eslint-plugin-storybook': ^9.0.9
  tailwindcss4:
    'tailwindcss': ^4.1.8
    '@tailwindcss/vite': ^4.1.8

patchedDependencies:
  unplugin-dts: patches/unplugin-dts.patch
  eslint-plugin-storybook: patches/eslint-plugin-storybook.patch

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
