packages:
  - packages/*
  - packages-scripts/*
  - apps-web/*
  - apps-server/*

catalog:
  '@cspell/eslint-plugin': ^9.0.2
  '@eslint/css': ^0.8.1
  '@eslint/js': ^9.28.0
  '@microsoft/api-extractor': ^7.52.8
  '@storybook/builder-vite': ^9.0.15
  '@storybook/react-vite': ^9.0.15
  '@tailwindcss/vite': ^4.1.8
  '@types/eslint': ^9.6.1
  '@types/eslint-config-prettier': ^6.11.3
  '@types/node': ^22.15.29
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  '@vitejs/plugin-react-swc': ^3.10.1
  clsx: ^2.1.1
  eslint: ^9.28.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-prettier: ^5.4.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-storybook: ^9.0.9
  globals: ^16.2.0
  motion: ^12.18.1
  prettier: ^3.5.3
  prettier-plugin-organize-imports: ^4.1.0
  prettier-plugin-tailwindcss: ^0.6.12
  react: ^19.1.0
  react-dom: ^19.1.0
  react-scan: ^0.3.4
  storybook: ^9.0.15
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.8
  typescript: ^5.8.3
  typescript-eslint: ^8.33.1
  usehooks-ts: ^3.1.1
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.0
  tsx: ^4.20.3
  '@pnpm/workspace.pkgs-graph': ^1000.0.15
  '@pnpm/lockfile.fs': ^1001.1.14
  '@pnpm/types': ^1000.6.0
  next: ^15.3.5
  '@eslint/eslintrc': ^3.3.1
  eslint-config-next: ^15.3.5
  '@next/eslint-plugin-next': ^15.3.5
  '@tailwindcss/postcss': ^4.1.11

catalogMode: strict

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

patchedDependencies:
  eslint-plugin-storybook: patches/eslint-plugin-storybook.patch
  next: patches/next.patch
