packages:
  - packages/*
  - packages-scripts/*
  - apps-web/*
  - apps-server/*

catalog:
  '@eslint/css': ^0.8.1
  '@eslint/js': ^9.33.0
  '@faker-js/faker': 9.9.0
  '@mdx-js/language-service': ^0.7.1
  '@microsoft/api-extractor': ^7.52.10
  '@next/eslint-plugin-next': 15.4.1
  '@opennextjs/cloudflare': ^1.6.5
  '@pnpm/lockfile.fs': ^1001.1.17
  '@pnpm/types': ^1000.7.0
  '@pnpm/workspace.pkgs-graph': ^1000.0.18
  '@react-hookz/web': ^25.1.1
  '@storybook/addon-docs': ^9.1.1
  '@storybook/builder-vite': ^9.1.1
  '@storybook/react-vite': ^9.1.1
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@types/eslint': ^9.6.1
  '@types/eslint-config-prettier': ^6.11.3
  '@types/mdx': ^2.0.13
  '@types/node': ^22.17.1
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  '@typescript-eslint/types': ^8.39.0
  '@vitejs/plugin-react-swc': ^3.11.0
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  eslint: ^9.33.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-mdx: ^3.6.2
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-storybook: ^9.1.1
  globals: ^16.3.0
  lucide-react: ^0.525.0
  motion: ^12.23.12
  next: ^15.4.6
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.2.0
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.1.1
  react-dom: ^19.1.1
  react-scan: ^0.3.6
  react-usestateref: ^1.0.9
  sonner: ^2.0.7
  storybook: ^9.1.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  tsx: ^4.20.3
  tw-animate-css: ^1.3.6
  typescript: ^5.8.3
  typescript-eslint: ^8.39.0
  usehooks-ts: 3.1.1
  vite: ^6.3.5
  vitest: ^3.2.4
  wrangler: ^4.28.1
  zod: ^3.25.76
  zx: ^8.8.0

catalogMode: strict

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

patchedDependencies:
  eslint-plugin-storybook: patches/eslint-plugin-storybook.patch
  next: patches/next.patch
