packages:
  - packages/*
  - packages-scripts/*
  - apps-web/*
  - apps-server/*

catalog:
  '@dicebear/collection': ^9.2.4
  '@dicebear/core': ^9.2.4
  '@eslint/css': ^0.14.0
  '@eslint/js': ^9.38.0
  '@faker-js/faker': 10.1.0
  '@mdx-js/language-service': ^0.7.3
  '@microsoft/api-extractor': ^7.52.10
  '@next/eslint-plugin-next': 16.0.1
  '@opennextjs/cloudflare': ^1.11.0
  '@pnpm/lockfile.fs': ^1001.1.21
  '@pnpm/types': ^1000.9.0
  '@pnpm/workspace.pkgs-graph': ^1000.0.25
  '@react-hookz/web': ^25.1.1
  '@storybook/addon-docs': ^10.0.1
  '@storybook/builder-vite': ^10.0.1
  '@storybook/react-vite': ^10.0.1
  '@tailwindcss/postcss': ^4.1.16
  '@tailwindcss/vite': ^4.1.16
  '@types/eslint': ^9.6.1
  '@types/eslint-config-prettier': ^6.11.3
  '@types/mdx': ^2.0.13
  '@types/node': 24.9.2
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  '@typescript-eslint/types': ^8.46.2
  '@vitejs/plugin-react-swc': ^4.2.0
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  es-toolkit: ^1.41.0
  eslint: ^9.38.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-better-tailwindcss: ^3.7.10
  eslint-plugin-mdx: ^3.6.2
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-storybook: ^10.0.1
  globals: ^16.4.0
  lucide-react: ^0.548.0
  motion: ^12.23.24
  nanoid: ^5.1.6
  next: ^16.0.1
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.3.0
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.2.0
  react-dom: ^19.2.0
  react-scan: ^0.4.3
  react-usestateref: ^1.0.9
  sonner: ^2.0.7
  storybook: ^10.0.1
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.16
  tsx: ^4.20.6
  tw-animate-css: ^1.4.0
  typescript: 5.9.3
  typescript-eslint: ^8.46.2
  usehooks-ts: 3.1.1
  vite: ^7.1.12
  vitest: ^4.0.5
  wrangler: ^4.45.2
  zod: ^3.25.76
  zx: ^8.8.5

catalogMode: strict

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

patchedDependencies:
  next: patches/next.patch
