packages:
  - packages/*
  - apps/*

catalog:
  typescript: ^5.8.3
  vite: ^6.3.5
  vitest: ^3.2.0
  vite-tsconfig-paths: ^5.1.4
  '@vitejs/plugin-react-swc': ^3.10.1
  '@types/node': ^22.15.29
  motion: ^12.18.1
  react-scan: 0.3.4
  usehooks-ts: ^3.1.1
  '@microsoft/api-extractor': ^7.52.8
  clsx: 2.1.1
  tailwind-merge: 3.3.1
  '@cspell/eslint-plugin': ^9.0.2
  '@eslint/css': ^0.8.1
  '@eslint/js': ^9.28.0
  '@types/eslint': ^9.6.1
  '@types/eslint-config-prettier': ^6.11.3
  eslint: ^9.28.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-prettier: ^5.4.1
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  globals: ^16.2.0
  prettier: ^3.5.3
  prettier-plugin-organize-imports: ^4.1.0
  prettier-plugin-tailwindcss: ^0.6.12
  typescript-eslint: ^8.33.1
  '@storybook/react-vite': 9.0.15
  '@storybook/builder-vite': ^9.0.15
  storybook: ^9.0.15

catalogMode: strict

catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5
  storybook9:
    storybook: ^9.0.9
    '@storybook/builder-vite': ^9.0.9
    '@storybook/react-vite': ^9.0.9
    eslint-plugin-storybook: ^9.0.9
  tailwindcss4:
    tailwindcss: ^4.1.8
    '@tailwindcss/vite': ^4.1.8

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

patchedDependencies:
  eslint-plugin-storybook: patches/eslint-plugin-storybook.patch
