packages:
  - packages/*
  - packages-scripts/*
  - apps-web/*
  - apps-server/*

catalog:
  '@dicebear/collection': ^9.2.4
  '@dicebear/core': ^9.2.4
  '@eslint/css': ^0.14.1
  '@eslint/js': ^9.39.1
  '@faker-js/faker': 10.1.0
  '@mdx-js/language-service': ^0.7.3
  '@microsoft/api-extractor': ^7.52.10
  '@next/eslint-plugin-next': 16.0.3
  '@opennextjs/cloudflare': ^1.13.1
  '@pnpm/lockfile.fs': ^1001.1.24
  '@pnpm/types': ^1001.0.1
  '@pnpm/workspace.pkgs-graph': ^1000.0.28
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-slider': ^1.3.6
  '@react-hookz/web': ^25.2.0
  '@storybook/addon-docs': ^10.0.8
  '@storybook/builder-vite': ^10.0.8
  '@storybook/react-vite': ^10.0.8
  '@tailwindcss/postcss': ^4.1.17
  '@tailwindcss/vite': ^4.1.17
  '@types/eslint': ^9.6.1
  '@types/eslint-config-prettier': ^6.11.3
  '@types/mdx': ^2.0.13
  '@types/node': 24.10.1
  '@types/react': ^19.2.6
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/types': ^8.47.0
  '@vitejs/plugin-react-swc': ^4.2.2
  class-variance-authority: 0.7.1
  clsx: ^2.1.1
  es-toolkit: ^1.42.0
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-better-tailwindcss: ^3.7.11
  eslint-plugin-mdx: ^3.6.2
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-storybook: ^10.0.8
  figma-squircle: ^1.1.0
  globals: ^16.5.0
  lucide-react: ^0.554.0
  motion: ^12.23.24
  nanoid: ^5.1.6
  next: ^16.0.3
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.3.0
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.2.0
  react-dom: ^19.2.0
  react-scan: ^0.4.3
  react-usestateref: ^1.0.9
  sonner: ^2.0.7
  storybook: ^10.0.8
  tailwind-merge: ^3.4.0
  tailwindcss: 4.1.17
  tsx: ^4.20.6
  tw-animate-css: ^1.4.0
  typescript: 5.9.3
  typescript-eslint: ^8.47.0
  usehooks-ts: 3.1.1
  vite: ^7.2.4
  vitest: ^4.0.12
  wrangler: ^4.50.0
  zod: ^3.25.76
  zx: ^8.8.5

catalogMode: strict

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

patchedDependencies:
  next: patches/next.patch
