packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  typescript: ^5.8.3
  vite: ^6.3.5
  vitest: ^3.2.0
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4.1.8
  vite-tsconfig-paths: ^5.1.4
  '@vitejs/plugin-react-swc': ^3.10.1
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  '@types/node': ^22.15.29
  '@tailwindcss/vite': ^4.1.8
