# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint, typecheck, and test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint and typecheck

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js with corepack
        uses: ./.github/actions/setup-node

      - name: Setup cache
        uses: ./.github/actions/setup-cache

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Pre-build dependencies
        run: pnpm run build:tsc

      - name: Build & typecheck
        run: pnpm run build

      - name: Run ESLint
        run: pnpm run lint:eslint:root

  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js with corepack
        uses: ./.github/actions/setup-node

      - name: Setup cache
        uses: ./.github/actions/setup-cache

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Pre-build dependencies
        run: pnpm run build:tsc

      - name: Build & typecheck
        run: pnpm run build

      - name: Run tests
        run: pnpm run test
